package com.zatec.thrones.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryDark = Color(0xFF242424)
val OnPrimaryDark = Color(0xFFFFFFFF)
val PrimaryContainerDark = Color(0xFF444444)
val OnPrimaryContainerDark = Color(0xFFFCFCFC)
val InversePrimaryDark = Color(0xFFDADADA)
val SecondaryDark = Color(0xFF461523)
val OnSecondaryDark = Color(0xFFFFF4F7)
val SecondaryContainerDark = Color(0xFF350613)
val OnSecondaryContainerDark = Color(0xFFF79C9C)
val TertiaryDark = Color(0xFF025E6F)
val OnTertiaryDark = Color(0xFFF8F8F8)
val TertiaryContainerDark = Color(0xFF112C31)
val OnTertiaryContainerDark = Color(0xFFBAF3FE)
val BackgroundDark = Color(0xFF111111)
val OnBackgroundDark = Color(0xFFEEEEEE)
val SurfaceDark = Color(0xFF272727)
val OnSurfaceDark = Color(0xFFF1F1F1)
val SurfaceVariantDark = Color(0xA4303030)
val OnSurfaceVariantDark = Color(0xFFC2C2C2)
val InverseSurfaceDark = Color(0xFFC0C0C0)
val InverseOnSurfaceDark = Color(0xFF353535)
val ErrorContainerDark = Color(0xFFF09595)
val OnErrorContainerDark = Color(0xFF521F1F)
val OutlineDark = Color(0xFF3D3D3D)

val PrimaryLight = Color(0xFF6650a4)
val OnPrimaryLight = Color(0xFFEFB8C8)
val PrimaryContainerLight = Color(0xFFEFB8C8)
val OnPrimaryContainerLight = Color(0xFFEFB8C8)
val InversePrimaryLight = Color(0xFFEFB8C8)
val SecondaryLight = Color(0xFFCCC2DC)
val OnSecondaryLight = Color(0xFFEFB8C8)
val SecondaryContainerLight = Color(0xFFEFB8C8)
val OnSecondaryContainerLight = Color(0xFFEFB8C8)
val TertiaryLight = Color(0xFFEFB8C8)
val OnTertiaryLight = Color(0xFFEFB8C8)
val TertiaryContainerLight = Color(0xFFEFB8C8)
val OnTertiaryContainerLight = Color(0xFFEFB8C8)
val BackgroundLight = Color(0xFFEFB8C8)
val OnBackgroundLight = Color(0xFFEFB8C8)
val SurfaceLight = Color(0xFFEFB8C8)
val OnSurfaceLight = Color(0xFFEFB8C8)
val SurfaceVariantLight = Color(0xFFEFB8C8)
val OnSurfaceVariantLight = Color(0xFFEFB8C8)
val InverseSurfaceLight = Color(0xFFEFB8C8)
val InverseOnSurfaceLight = Color(0xFFEFB8C8)
val ErrorContainerLight = Color(0xFFEFB8C8)
val OnErrorContainerLight = Color(0xFFEFB8C8)
val OutlineLight = Color(0xFFEFB8C8)