package com.zatec.thrones.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryDark = Color(0xFF242424)
val OnPrimaryDark = Color(0xFFFFFFFF)
val PrimaryContainerDark = Color(0xFF444444)
val OnPrimaryContainerDark = Color(0xFFFCFCFC)
val InversePrimaryDark = Color(0xFFDADADA)
val SecondaryDark = Color(0xFF461523)
val OnSecondaryDark = Color(0xFFFFF4F7)
val SecondaryContainerDark = Color(0xFF350613)
val OnSecondaryContainerDark = Color(0xFFF79C9C)
val TertiaryDark = Color(0xFF025E6F)
val OnTertiaryDark = Color(0xFFF8F8F8)
val TertiaryContainerDark = Color(0xFF112C31)
val OnTertiaryContainerDark = Color(0xFFBAF3FE)
val BackgroundDark = Color(0xFF111111)
val OnBackgroundDark = Color(0xFFEEEEEE)
val SurfaceDark = Color(0xFF272727)
val OnSurfaceDark = Color(0xFFF1F1F1)
val SurfaceVariantDark = Color(0x751D1D1D)
val OnSurfaceVariantDark = Color(0xFFC2C2C2)
val InverseSurfaceDark = Color(0xFFC0C0C0)
val InverseOnSurfaceDark = Color(0xFF353535)
val ErrorContainerDark = Color(0xFFF09595)
val OnErrorContainerDark = Color(0xFF521F1F)
val OutlineDark = Color(0xFF3D3D3D)

val PrimaryLight = Color(0xFFEEEEEE)
val OnPrimaryLight = Color(0xFF1B1B1B)
val PrimaryContainerLight = Color(0xFFEDEDED)
val OnPrimaryContainerLight = Color(0xFF2E2E2E)
val InversePrimaryLight = Color(0xFF2B2B2B)
val SecondaryLight = Color(0xFF964848)
val OnSecondaryLight = Color(0xFFFEF3F6)
val SecondaryContainerLight = Color(0xFFFDF7F7)
val OnSecondaryContainerLight = Color(0xFF552828)
val TertiaryLight = Color(0xFF8DE8F9)
val OnTertiaryLight = Color(0xFF112C31)
val TertiaryContainerLight = Color(0xFF8EE9FA)
val OnTertiaryContainerLight = Color(0xFF112C31)
val BackgroundLight = Color(0xFFE6E6E6)
val OnBackgroundLight = Color(0xFF2B2B2B)
val SurfaceLight = Color(0xFFECECEC)
val OnSurfaceLight = Color(0xFF1B1B1B)
val SurfaceVariantLight = Color(0x75FFFFFF)
val OnSurfaceVariantLight = Color(0xFF2B2B2B)
val InverseSurfaceLight = Color(0xFF1B1B1B)
val InverseOnSurfaceLight = Color(0xFFECECEC)
val ErrorContainerLight = Color(0xFFFDC1C1)
val OnErrorContainerLight = Color(0xFF6F0808)
val OutlineLight = Color(0xFFC1C1C1)